# mkdir logs; docker-compose down && HOST_UID=$(id -u) docker-compose up
version: '2.4'
services:
  log-example:
    image: datajoint/djbase:py3.9-alpine
    user: ${HOST_UID}:anaconda
    environment:
      - LOG_LEVEL=DEBUG
    volumes:
      - ./example.py:/main/example.py
      - ./new_logging.py:/main/new_logging.py
      - ./utils.py:/main/utils.py
      - ./logs:/main/logs
    command: ./example.py
